services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8081:8080
      - 443:443
    volumes:
      - f3m_Storage:/Storage
      - ./appsettings.json:/app/appsettings.json

volumes:
  f3m_Storage:
