<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<SourceRevisionId>$([System.DateTime]::UtcNow.ToString("yyyy/MM/dd"))</SourceRevisionId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
		<PackageReference Include="FlanderDev.RouteGen.Abstractions" Version="0.5.1" />
		<PackageReference Include="FlanderDev.RouteGen.Generators" Version="0.5.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<AdditionalFiles Include="..\*.Client\**\*.razor" Visible="false" />
	</ItemGroup>
</Project>
